name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]

    env:
      FLUID_TEST_COUCH_USE_EXTERNAL: true
      BROWSERS: chrome

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Node Tests
        run: npm run test:node
        timeout-minutes: 2

      - name: Debug
        run: docker ps -a
        if: ${{ always() }}

      - name: Debug 2
        run: sudo netstat -antp | grep LISTEN
        if: ${{ always() }}

      - name: Browser Tests
        run: npm run test:webdriver
        if: ${{ always() }}
